name: toponet_resnet18_supervised
output_dir: checkpoints/toponet/resnet18_taskonly
wandb: False
spatial_loss:
  name: 2d_spatial_correlation
  spatial_weight:
    layer1.0.conv1: 0.
    layer1.0.conv2: 0.
    layer1.1.conv1: 0.
    layer1.1.conv2: 0.
    layer2.0.conv1: 0.
    layer2.0.conv2: 0.
    layer2.1.conv1: 0.
    layer2.1.conv2: 0.
    layer3.0.conv1: 0.
    layer3.0.conv2: 0.
    layer3.1.conv1: 0.
    layer3.1.conv2: 0.
    layer4.0.conv1: 0.
    layer4.0.conv2: 0.
    layer4.1.conv1: 0.
    layer4.1.conv2: 0.
  position_dir: checkpoints/toponet/resnet18_spatial/positions
variant:
  name: tdann
  architecture: resnet18
  params:
    pretrained_weights: checkpoints/tdann/supervised/supervised.pth
    dataset_path: ImageNet:split=TRAIN:root=/data/ynshah/imagenet/:extra=/data/ynshah/imagenet/extra