name: tdann_optimized
output_dir: checkpoints/tdann/seed_4/
wandb: False
spatial_loss:
  name: 2d_spatial_correlation
  spatial_weight: 0.
  position_dir: checkpoints/tdann/positions/swappedon_SineGrating2019
variant:
  name: tdann
  architecture: resnet18
  params:
    pretrained_weights: checkpoints/tdann/spatial/model_final_checkpoint_phase199_seed4.torch
    dataset_path: ImageNet:split=TRAIN:root=/data/ynshah/imagenet/:extra=/data/ynshah/imagenet/extra
