name: tdann
output_dir: checkpoints/tdann/task_only_seed1/
wandb: False
spatial_loss:
  name: 2d_spatial_correlation
  spatial_weight:
    layer1.0: 0.
    layer1.1: 0.
    layer2.0: 0.
    layer2.1: 0.
    layer3.0: 0.
    layer3.1: 0.
    layer4.0: 0.
    layer4.1: 0.
  position_dir: checkpoints/tdann/positions
swapopt:
  num_steps: 100000000
  steps_per_neighborhood: 500
variant:
  name: tdann
  architecture: resnet18
  params:
    pretrained_weights: /ccn2/u/ynshah/retinospace/checkpoints/resnet18_simclr_imagenet_seed1/model_final_checkpoint_phase199.torch
    dataset_path: ImageNet:split=TRAIN:root=/data/ynshah/imagenet/:extra=/data/ynshah/imagenet/extra
    config: tdann_taskonly_config.yaml
