name: tdann
output_dir: checkpoints/tdann/
wandb: False
spatial_loss:
  name: 2d_spatial_correlation
  spatial_weight: 0.
  position_dir: checkpoints/tdann/positions
variant:
  name: tdann
  architecture: resnet18
  params:
    pretrained_weights: checkpoints/tdann/pretrained/model_final_checkpoint_phase199.torch
    dataset_path: ImageNet:split=TRAIN:root=/data/ynshah/imagenet/:extra=/data/ynshah/imagenet/extra
