name: swinv2_base_simmim_imagenet_unoptimized
output_dir: checkpoints/swinv2_base_simmim_imagenet_unoptimized
wandb: False
spatial_loss:
  name: 2d_spatial_correlation
  spatial_weight:
    layers.0.blocks.0: 0.
    layers.0.blocks.1: 0.
    layers.1.blocks.0: 0.
    layers.1.blocks.1: 0.
    layers.2.blocks.0: 0.
    layers.2.blocks.1: 0.
    layers.2.blocks.2: 0.
    layers.2.blocks.3: 0.
    layers.2.blocks.4: 0.
    layers.2.blocks.5: 0.
    layers.2.blocks.6: 0.
    layers.2.blocks.7: 0.
    layers.2.blocks.8: 0.
    layers.2.blocks.9: 0.
    layers.2.blocks.10: 0.
    layers.2.blocks.11: 0.
    layers.2.blocks.12: 0.
    layers.2.blocks.13: 0.
    layers.2.blocks.14: 0.
    layers.2.blocks.15: 0.
    layers.2.blocks.16: 0.
    layers.2.blocks.17: 0.
    layers.3.blocks.0: 0.
    layers.3.blocks.1: 0.
  position_dir: checkpoints/swinv2_base_simmim_imagenet/positions
swapopt:
  num_steps: 100000000
  steps_per_neighborhood: 500
variant:
  name: swinv2_simmim
  architecture: swinv2_base
  setup:
    train: ../Swin-Transformer/main_simmim_pt.py
    model: ../Swin-Transformer/models/build.py
    eval_model: ../Swin-Transformer/models/build.py
    config: ../Swin-Transformer/config.py
    eval: ""
  params:
    config: ../Swin-Transformer/configs/simmim/simmim_pretrain__swinv2_base__img192_window12__800ep.yaml
    pretrained_weights: ""
    resume_path: ""
    dataset_path: /data/ynshah/imagenet/train