name: llcnn
output_dir: checkpoints/llcnn
wandb: False
spatial_loss:
  name: 2d_spatial_correlation
  spatial_weight:
    layer1.0.conv1: 0.
    layer1.0.conv2: 0.
    layer1.1.conv1: 0.
    layer1.1.conv2: 0.
    layer2.0.conv1: 0.
    layer2.0.conv2: 0.
    layer2.1.conv1: 0.
    layer2.1.conv2: 0.
    layer3.0.conv1: 0.
    layer3.0.conv2: 0.
    layer3.1.conv1: 0.
    layer3.1.conv2: 0.
    layer4.0.conv1: 0.
    layer4.0.conv2: 0.
    layer4.1.conv1: 0.
    layer4.1.conv2: 0.
  position_dir: checkpoints/llcnn/positions
variant:
  name: llcnn
  architecture: resnet18
  params:
    pretrained_weights: checkpoints/llcnn/resnet18contopo_LLC_car_90.pt
    dataset_path: ImageNet:split=TRAIN:root=/data/ynshah/imagenet/:extra=/data/ynshah/imagenet/extra