name: vitb16_mocov3_imagenet_noswapopt_lwx1
output_dir: checkpoints/vitb16_mocov3_imagenet_noswapopt_lwx1
wandb: False
spatial_loss:
  name: 2d_spatial_correlation
  spatial_weight:
    blocks.0: 0.25
    blocks.1: 0.25
    blocks.2: 0.25
    blocks.3: 0.25
    blocks.4: 0.25
    blocks.5: 0.25
    blocks.6: 0.25
    blocks.7: 0.25
    blocks.8: 0.25
    blocks.9: 0.25
    blocks.10: 0.25
    blocks.11: 0.25
  position_dir: checkpoints/vitb16_mocov3_imagenet/positions
swapopt:
  num_steps: 100000000
  steps_per_neighborhood: 500
variant:
  name: mocov3
  architecture: vitb16
  setup:
    train: ../moco-v3/main_moco.py
    model: ../moco-v3/main_moco.py
    eval_model: ../moco-v3/vits.py
    config: ""
    eval: ../moco-v3/main_lincls.py
  params:
    config: ""
    pretrained_weights: checkpoints/vitb16_mocov3_imagenet_noswapopt_lwx1/vitb16_mocov3_imagenet_noswapopt_lwx1.pth.tar
    resume_path: ""
    dataset_path: /data2/ynshah/imagenet/