name: cvt_base_a_supervised_imagenet_unoptimized
output_dir: checkpoints/cvt_base_a_supervised_imagenet_unoptimized
wandb: False
spatial_loss:
  name: 2d_spatial_correlation
  spatial_weight:
    stage0.blocks.0.attn: 0.
    stage1.blocks.0.attn: 0.
    stage1.blocks.1.attn: 0.
    stage2.blocks.0.attn: 0.
    stage2.blocks.1.attn: 0.
    stage2.blocks.2.attn: 0.
    stage2.blocks.3.attn: 0.
    stage2.blocks.4.attn: 0.
    stage2.blocks.5.attn: 0.
    stage2.blocks.6.attn: 0.
    stage2.blocks.7.attn: 0.
    stage2.blocks.8.attn: 0.
    stage2.blocks.9.attn: 0.
  position_dir: checkpoints/cvt_base_a_supervised_imagenet/positions
swapopt:
  num_steps: 100000000
  steps_per_neighborhood: 500
variant:
  name: cvt
  architecture: cvt_base_a
  setup:
    train: ""
    model: ""
    eval_model: ""
    config: ""
    eval: ""
  params:
    config: configs/config/cvt-13-224x224.yaml
    pretrained_weights: ""
    resume_path: ""
    dataset_path: /data/ynshah/imagenet/train