name: cvt_base_supervised_imagenet_swapopt
output_dir: checkpoints/cvt_base_supervised_imagenet/positions/swappedon_SineGrating2019
wandb: False
spatial_loss:
  name: 2d_spatial_correlation
  spatial_weight:
    stage0.blocks.0: 0.
    stage1.blocks.0: 0.
    stage1.blocks.1: 0.
    stage2.blocks.0: 0.
    stage2.blocks.1: 0.
    stage2.blocks.2: 0.
    stage2.blocks.3: 0.
    stage2.blocks.4: 0.
    stage2.blocks.5: 0.
    stage2.blocks.6: 0.
    stage2.blocks.7: 0.
    stage2.blocks.8: 0.
    stage2.blocks.9: 0.
  position_dir: checkpoints/cvt_base_supervised_imagenet/positions/swappedon_SineGrating2019
swapopt:
  num_steps: 100000000
  steps_per_neighborhood: 500
variant:
  name: cvt
  architecture: cvt_base
  setup:
    train: ""
    model: ""
    eval_model: ""
    config: ""
    eval: ""
  params:
    config: configs/config/cvt-13-224x224.yaml
    pretrained_weights: checkpoints/cvt_base_supervised_imagenet/cvt_base_supervised_imagenet.pth
    resume_path: ""
    dataset_path: /data/ynshah/imagenet/train