name: vitb14am_dinov2_imagenet_unoptimized
output_dir: checkpoints/vitb14_dinov2_imagenet_unoptimized
wandb: False
spatial_loss:
  name: 2d_spatial_correlation
  spatial_weight:
    blocks.0.attn: 0.
    blocks.1.attn: 0.
    blocks.2.attn: 0.
    blocks.3.attn: 0.
    blocks.4.attn: 0.
    blocks.5.attn: 0.
    blocks.6.attn: 0.
    blocks.7.attn: 0.
    blocks.8.attn: 0.
    blocks.9.attn: 0.
    blocks.10.attn: 0.
    blocks.11.attn: 0.
  position_dir: checkpoints/vitb14am_dinov2_imagenet/positions/
variant:
  name: dinov2
  architecture: vitb14
  setup:
    train: dinov2.train.train.do_train
    model: dinov2.train.ssl_meta_arch.SSLMetaArch
    eval_model: dinov2.eval.setup.setup_and_build_model
    config: dinov2.utils.config.setup
    eval: dinov2.eval.linear.run_eval_linear
  params:
    config: ../dinov2/dinov2/configs/train/vitb14_short.yaml
    pretrained_weights: ""
    dataset_path: ImageNet:split=TRAIN:root=/data/ynshah/imagenet/:extra=/data/ynshah/imagenet/extra
